#!/bin/sh
# vim: set ft=sh

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

source $(dirname $0)/common.sh

# for jq
PATH=/usr/local/bin:$PATH

payload=$TMPDIR/gerrit-resource-request
cat > $payload <&0

load_pubkey $payload
configure_git_ssl_verification $payload
configure_credentials $payload

# Fetch metadata from JSON
hostname=$(jq -r '.source.hostname // ""' < $payload)
port=$(jq -r '.source.port // 29418' < $payload)
username=$(jq -r '.source.username // ""' < $payload)
query=$(jq -r '.source.query // "status:open"' < $payload)
ref=$(jq -r '.version.ref // ""' < $payload)

# Format URL
if [ -n "$hostname" ]; then
  url="$hostname"
  if [ -n "$username" ]; then
      url="$username@$url"
  fi
fi

result=$(ssh -p $port $url gerrit query $query --format=JSON --current-patch-set | jq -s 'sort_by(.currentPatchSet.createdOn) | .[].currentPatchSet.revision | select(. != null)' | jq -s 'map({ref: .})')
echo "$result" >&3
