#!/bin/sh
# vim: set ft=sh

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

source $(dirname $0)/common.sh

# for jq
PATH=/usr/local/bin:$PATH

payload=$TMPDIR/gerrit-resource-request

cat > $payload <&0

load_pubkey $payload
# configure_git_ssl_verification $payload
# configure_credentials $payload

hostname=$(jq -r '.source.hostname // ""' < $payload)
port=$(jq -r '.source.port // 29418' < $payload)
username=$(jq -r '.source.username // ""' < $payload)
project=$(jq -r '.source.project // ""' < $payload)
# uri=$(jq -r '.source.uri // ""' < $payload)
branch=$(jq -r '.source.branch // ""' < $payload)
paths="$(jq -r '(.source.paths // ["."])[]' < $payload)" # those "'s are important
ignore_paths="$(jq -r '":!" + (.source.ignore_paths // [])[]' < $payload)" # these ones too
tag_filter=$(jq -r '.source.tag_filter // ""' < $payload)
git_config_payload=$(jq -r '.source.git_config // []' < $payload)
ref=$(jq -r '.version.ref // ""' < $payload)
skip_ci_disabled=$(jq -r '.source.disable_ci_skip // false' < $payload)
url="$hostname"
if [ -n "$username" ]; then
    url="$username@$url"
fi
uri="ssh://$url:$port/$project.git"
echo "uri=$uri"
#ssh://malston@192.168.99.103:29418/malston/concourse-ci-demo

configure_git_global "${git_config_payload}"

destination=$TMPDIR/gerrit-resource-repo-cache

if [ -d $destination ]; then
  cd $destination
  git fetch
  git reset --hard FETCH_HEAD
else
  branchflag=""
  if [ -n "$branch" ]; then
    branchflag="--branch $branch"
  fi

  git clone --single-branch $uri $branchflag $destination
  cd $destination
fi

if [ -n "$ref" ] && git cat-file -e "$ref"; then
  init_commit=$(git rev-list --max-parents=0 HEAD)
  if [ "${ref}" = "${init_commit}" ]; then
    log_range="--reverse HEAD"
  else
    log_range="--reverse ${ref}~1..HEAD"
  fi
else
  log_range="-1"
fi

if [ $paths = '.' ] && [ -z $ignore_paths ]; then
  paths_search=""
else
  paths_search="-- $paths $ignore_paths"
fi

ci_skip=""
if [ "$skip_ci_disabled" != "true" ]; then
  ci_skip="--grep \\[ci\sskip\\] --invert-grep"
fi

if [ -n "$tag_filter" ]; then
  {
    if [ -n "$ref" ]; then
      result=$(git tag --list '$tag_filter' --sort=creatordate --contains $ref) | jq -R '.' | jq -s "map({ref: .})"
    else
      result=$(git tag --list '$tag_filter' --sort=creatordate | tail -1) | jq -R '.' | jq -s "map({ref: .})"
    fi
  }
else
  {
    result=$(git log $ci_skip --format='%H' $log_range $paths_search) | jq -R '.' | jq -s "map({ref: .})"
  }
fi
echo "$result"

# Check for any open changes that have been made to the project
query="status:open"
append_to_query() {
    if [ -n "$2" ]; then
        query="$query $1:$2"
    fi
}
append_to_query 'branch' $branch
append_to_query 'project' $project
gerrit="ssh -p $port $url gerrit"

if [ -n "$ref" ]; then
    last_time=$($gerrit query $query commit:$ref --format=TEXT --current-patch-set | grep '^    createdOn' | cut -d ':' -f 2-)
    append_to_query 'since' $last_time
fi

result=$($gerrit query $query --format=JSON --current-patch-set | jq -s 'sort_by(.currentPatchSet.createdOn) | .[].currentPatchSet.revision | select(. != null)' | jq -s 'map({ref: .})')
echo "$result"
echo "$result" >&3
