#!/bin/sh
# vim: set ft=sh

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

source $(dirname $0)/common.sh

source=$1

if [ -z "$source" ]; then
  echo "usage: $0 <path/to/source>" >&2
  exit 1
fi

# for jq
PATH=/usr/local/bin:$PATH

payload=$(mktemp $TMPDIR/gerrit-resource-request.XXXXXX)

cat > $payload <&0

load_pubkey $payload

hostname=$(jq -r '.source.hostname // ""' < $payload)
port=$(jq -r '.source.port // 29418' < $payload)
username=$(jq -r '.source.username // ""' < $payload)
repository=$(jq -r '.params.repository // ""' < $payload)
verified=$(jq -r '.params.verified // "0"' < $payload)

cd $source/$repository
version=$(git rev-parse HEAD)
project=$(git remote show origin -n | grep "Fetch URL:" | sed -E 's#^.*/(.*)$#\1#' | sed 's#.git$##')

ssh $hostname -p $port -l $username gerrit review --verified $verified $version

echo -n '{
  "version": { "ref": "'"$version"'", project: "'"$project"'" },
  "metadata": [
    { "name": "commit", "value": "'"$version"'" },
    { "name": "verified", "value": "'"$verified"'" }
  ]
}' >&3
