#!/bin/sh
# vim: set ft=sh

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

source $(dirname $0)/common.sh

source=$1

if [ -z "$source" ]; then
  echo "usage: $0 <path/to/source>" >&2
  exit 1
fi

# for jq
PATH=/usr/local/bin:$PATH

payload=$(mktemp $TMPDIR/gerrit-resource-request.XXXXXX)

cat > $payload <&0

load_pubkey $payload

branch=$(jq -r '.source.branch // ""' < $1)
hostname=$(jq -r '.source.hostname // ""' < $1)
port=$(jq -r '.source.port // 29418' < $1)
project=$(jq -r '.source.project // ""' < $1)
username=$(jq -r '.source.username // ""' < $1)
verified=$(jq -r '.params.verified // "+1"' < $payload)

cd $source
version=$(git rev-parse HEAD)

ssh $hostname -p $port -l $username gerrit review --verified $verified $version

echo -n '{
  "version": { "ref": "'"$version"'" },
  "metadata": [
    { "name": "commit", "value": "'"$version"'" },
    { "name": "verified", "value": "'"$verified"'" }
  ]
}' >&3
